# Generated by Django 3.2.25 on 2024-09-09 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_recipe'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='desciprion',
            new_name='description',
        ),
    ]
